// export const Sign_Up_Fields = [
// 	{
// 		id: 1,
// 		haveError: formik.errors.first_name,
// 		holder: "First name",
// 		isRequired: true,
// 		isTouched: formik.touched.first_name,
// 		name: "first_name",
// 		type: "text",
// 	},
// 	{
// 		id: 2,
// 		haveError: formik.errors.last_name,
// 		holder: "Last name",
// 		isRequired: true,
// 		isTouched: formik.touched.last_name,
// 		name: "last_name",
// 		type: "text",
// 	},
// 	{
// 		id: 3,
// 		haveError: formik.errors.phone,
// 		holder: "Phone",
// 		isRequired: true,
// 		isTouched: formik.touched.phone,
// 		name: "phone",
// 		type: "tel",
// 	},
// 	{
// 		id: 4,
// 		haveError: formik.errors.email,
// 		holder: "Email",
// 		isRequired: true,
// 		isTouched: formik.touched.email,
// 		name: "email",
// 		type: "email",
// 	},
// 	{
// 		id: 5,
// 		haveError: formik.errors.password,
// 		holder: "Password",
// 		isRequired: true,
// 		isTouched: formik.touched.password,
// 		name: "password",
// 		type: "password",
// 	},
// ];
